export const types = {
  CORRECT_GUESS: "CORRECT_GUESS",
  GUESS_WORD: "GUESS_WORD",
  SET_SECRET_WORD: "SET_SECRET_WORD",
  RESET_GAME: "RESET_GAME",
  GIVE_UP: "GIVE_UP",
  CUSTOM_SECRET_WORD: "CUSTOM_SECRET_WORD",
  SERVER_ERROR: "SERVER_ERROR",
  IS_FETCHING: "IS_FETCHING",
};
